spring:
  application:
    name: fooder
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:fooder;mode=mysql
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
