DROP TABLE IF EXISTS STORE;
CREATE TABLE `STORE`
(
    `STORE_ID`         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    `NAME`             VARCHAR(100)                                        NOT NULL,
    `FOOD_CATEGORY`    VARCHAR(50)                                         NOT NULL,
    `TELEPHONE_NUMBER` VARCHAR(20)                                         NULL,
    `ZIP_CODE`         VARCHAR(5)                                          NOT NULL,
    `ADDRESS`          VARCHAR(255)                                        NOT NULL,
    `DETAIL_ADDRESS`   VARCHAR(255)                                        NOT NULL,
    `MIN_ORDER_PRICE`  SMALLINT                                            NOT NULL,
    `DELIVERY_PRICE`   SMALLINT                                            NOT NULL,
    `START_TIME`       TIME                                                NOT NULL,
    `FINISH_TIME`      TIME                                                NOT NULL
);



-- spring data jdbc test ddl
DROP TABLE MEMBER IF EXISTS CASCADE;
CREATE TABLE MEMBER
(
    ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    PHONE_NUMBER VARCHAR(20)                                     NOT NULL,
    NAME         VARCHAR(20)                                     NOT NULL,
    NICK_NAME    VARCHAR(20)                                     NOT NULL
)