CREATE TABLE `STORE`
(
    `ID`                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    `NAME`                VARCHAR(100)                                        NOT NULL,
    `FOOD_CATEGORY`       VARCHAR(50)                                         NOT NULL,
    `TELEPHONE_NUMBER`    VARCHAR(20)                                         NULL,
    `ZIP_CODE`            VARCHAR(5)                                          NOT NULL,
    `ADDRESS`             VARCHAR(255)                                        NOT NULL,
    `DETAIL_ADDRESS`      VARCHAR(255)                                        NOT NULL,
    `BIZ_NUMBER`          VARCHAR(10)                                         NOT NULL,
    `MIN_ORDER_PRICE`     SMALLINT                                            NOT NULL,
    `DELIVERY_PRICE`      SMALLINT                                            NOT NULL,
    `ORDER_POSSIBLE_TYPE` VARCHAR(50)                                         NOT NULL,
    `PAY_POSSIBLE_TYPE`   VARCHAR(50)                                         NOT NULL,
    `STATUS`              VARCHAR(50)                                         NOT NULL,
    `START_TIME`          VARCHAR(20)                                         NOT NULL,
    `FINISH_TIME`         VARCHAR(20)                                         NOT NULL,
    `OWNER_NOTIFICATION`  BLOB                                                NULL,
    `REGIST_DATETIME`     TIMESTAMP                                           NOT NULL,
    `UPDATE_DATETIME`     TIMESTAMP                                           NOT NULL
);
