DROP TABLE IF EXISTS STORE;
CREATE TABLE `STORE`
(
    `STORE_ID`         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    `NAME`             VARCHAR(100)                                     NOT NULL,
    `FOOD_CATEGORY`    VARCHAR(50)                                      NOT NULL,
    `TELEPHONE_NUMBER` VARCHAR(20) NULL,
    `ZIP_CODE`         VARCHAR(5)                                       NOT NULL,
    `ADDRESS`          VARCHAR(255)                                     NOT NULL,
    `DETAIL_ADDRESS`   VARCHAR(255)                                     NOT NULL,
    `MIN_ORDER_PRICE`  INT                                              NOT NULL,
    `DELIVERY_PRICE`   INT                                              NOT NULL,
    `START_TIME`       TIME                                             NOT NULL,
    `FINISH_TIME`      TIME                                             NOT NULL
);

DROP TABLE IF EXISTS MENU;
CREATE TABLE `MENU`
(
    `MENU_ID`               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    `STORE_ID`              INT                                              NOT NULL,
    `NAME`                  VARCHAR(100)                                     NOT NULL,
    `DESCRIPTION`           VARCHAR(255)                                     NOT NULL,
    `BASE_MENU_DESCRIPTION` VARCHAR(255) NULL,
    `PRICE`                 INT                                              NOT NULL
);

DROP TABLE IF EXISTS OPTION_GROUP_SPEC;
CREATE TABLE `OPTION_GROUP_SPEC`
(
    `OPTION_GROUP_SPEC_ID` INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    `MENU_ID`              INT                                              NOT NULL,
    `NAME`                 VARCHAR(100)                                     NOT NULL
);

DROP TABLE IF EXISTS OPTION_SPEC;
CREATE TABLE `OPTION_SPEC`
(
    `OPTION_SPEC_ID`       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    `OPTION_GROUP_SPEC_ID` INT                                              NOT NULL,
    `NAME`                 VARCHAR(100)                                     NOT NULL,
    `PRICE`                INT                                              NOT NULL
);

DROP TABLE IF EXISTS `ORDER`;
CREATE TABLE `ORDER`
(
    `ORDER_ID`     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    `USER_ID`      INT                                              NOT NULL,
    `STORE_ID`     INT                                              NOT NULL,
    `ORDERED_TIME` TIMESTAMP                                        NOT NULL,
    `ORDER_STATUS` VARCHAR(50)                                      NOT NULL
);

DROP TABLE IF EXISTS ORDER_ITEM;
CREATE TABLE `ORDER_ITEM`
(
    `ORDER_ITEM_ID` INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    `ORDER_ID`      INT                                  NOT NULL,
    `MENU_ID`       INT                                  NOT NULL,
    `MENU_NAME`     VARCHAR(100)                         NOT NULL,
    `MENU_PRICE`    INT                                  NOT NULL,
    `MENU_COUNT`    SMALLINT                             NOT NULL,
    PRIMARY KEY (ORDER_ITEM_ID, MENU_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES `ORDER` (ORDER_ID)
);

DROP TABLE IF EXISTS ORDER_OPTION_GROUP;
CREATE TABLE `ORDER_OPTION_GROUP`
(
    `ORDER_OPTION_GROUP_ID`   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    `ORDER_ITEM_ID`           INT                                  NOT NULL,
    `ORDER_OPTION_GROUP_NAME` VARCHAR(100)                         NOT NULL,
    CONSTRAINT PK_ORDER_OPTION_GROUP PRIMARY KEY (ORDER_OPTION_GROUP_ID, ORDER_ITEM_ID)
);

DROP TABLE IF EXISTS ORDER_OPTION;
CREATE TABLE `ORDER_OPTION`
(
    `ORDER_OPTION_ID`       INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    `ORDER_OPTION_GROUP_ID` INT                                  NOT NULL,
    `ORDER_OPTION_NAME`     VARCHAR(100)                         NOT NULL,
    `ORDER_OPTION_PRICE`    INT                                  NOT NULL,
    CONSTRAINT PK_ORDER_OPTION PRIMARY KEY (ORDER_OPTION_ID, ORDER_OPTION_GROUP_ID, ORDER_OPTION_NAME,
                                            ORDER_OPTION_PRICE)
);


-- spring data jdbc test ddl
DROP TABLE MEMBER IF EXISTS CASCADE;
CREATE TABLE MEMBER
(
    ID           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    PHONE_NUMBER VARCHAR(20)                                      NOT NULL,
    NAME         VARCHAR(20)                                      NOT NULL,
    NICK_NAME    VARCHAR(20)                                      NOT NULL
)
